version: '3.4'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - $PWD/nginx/auth_request.js:/etc/nginx/njs/auth_request.js
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf